### ISSUE TITLE
[BUG] Reporting Battery and Firmware 

### ISSUE THREAD

**Issue by DashCruft** [korkje/mow#1]
When trying to report the battery or firmware, I face this issue:

![image](https://user-images.githubusercontent.com/59381835/156910720-8236b8a5-1d96-4602-a296-5d574b2c5edc.png)

**Comment by DashCruft** [comment]
Running it as root (or sudo) seems to be fixing the error!

**Comment by korkje** [comment]
Thanks for bringing it up anyway, I will be looking at handling these kinds of errors in a friendly manner in the future, e.g. by displaying a message that says "hidapi was not found, here are the steps to install...", "this requires root privileges, try running with sudo" etc. I haven't tried running this on linux myself yet (and I don't need sudo on macOS for this), but it's probably possible to change permissions for access to hidapi or something. Will try to get back to you if i figure it out.

**Comment by korkje** [comment]
I came across this **nice** file in the hidapi repo; [/udev/69-hid.rules](https://github.com/libusb/hidapi/blob/master/udev/69-hid.rules). I haven't tried following that setup myself yet, but it seems to address your issue. If you end up trying it out, Glorious' VID is `258a`, and the PID is `2011` when wired and `2022` wireless, so you would need to set this up for both I guess.

**Comment by cglmrfreeman** [comment]
I'm on linux and attempting to edit the 69.hid.rules to no avail. Sudo functionality works, but not preferable if I'm going to create a wrapper around this cli.
