### ISSUE TITLE
getting warning: build failed, waiting for other jobs to finish when i try to install

### ISSUE THREAD

**Issue by Jeetylime** [korkje/mow#10]

**Comment by Jeetylime** [comment]
here is my cargo test.

jettf@Mint:~/mow$ cargo test
   Compiling proc-macro2 v1.0.36
   Compiling version_check v0.9.4
   Compiling unicode-xid v0.2.2
   Compiling libc v0.2.119
   Compiling syn v1.0.86
   Compiling autocfg v1.1.0
   Compiling memchr v2.4.1
   Compiling pkg-config v0.3.24
   Compiling cc v1.0.73
   Compiling heck v0.4.0
   Compiling lazy_static v1.4.0
   Compiling hashbrown v0.11.2
   Compiling textwrap v0.15.0
LLVM ERROR: IO failure on output stream: No space left on device
error: could not compile `cc`
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: IO failure on output stream: No space left on device
error: could not compile `textwrap`
jettf@Mint:~/mow$

**Comment by korkje** [comment]
Hi! Did you figure this out? I haven't much experience with Mint myself (I mainly use macOS), but from the output you provided it kind of looks like the folder where compilation is done is on a virtual/physical drive that is/gets full. I suspect the location is determined by the `TMPDIR` environment variable, but I am not sure.
