### ISSUE TITLE
An Open-Source License?

### ISSUE THREAD

**Issue by n3oney** [korkje/mow#16]
Hello, thank you for this project!
With the current state of the repository, the code is only for personal use, as it doesn't have a license.
```
However, without a license, the default copyright laws apply,
meaning that you retain all rights to your source code and
no one may reproduce, distribute, or create derivative works
from your work.
```
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

It would be great if you could add an open-source LICENSE to this project, meaning we all could use and improve this code!

**Comment by korkje** [comment]
Good point, I must've forgotten about that for this repo. Added MIT license now 👍
