### ISSUE TITLE
Rebind the "forward" button to LSHIFT

### ISSUE THREAD

**Issue by semedilino-073** [korkje/mow#18]
Hello,
I installed mow on Arch and I was trying to rebind my forward button to the LSHIFT, but I ran into some issues that I don't understand. Maybe I'm wrong and I hope so, it would be better. This is the command I'm using:
`mow config bind forward key key-code lshift`
But this error popped up:
`error: Invalid value "lshift" for '<KEY>': invalid digit found in string`
Do you have any solutions?

**Comment by korkje** [comment]
Hi! When using `key-code` you have to provide a number, looks to me like the code for both left and right shift is `16`. You can use a tool like [this one](https://www.toptal.com/developers/keycode) to look up key codes.

**Comment by semedilino-073** [comment]
Hi, thanks for the immediate answer! I didn't expect that, so I'm sorry for my late response.
I ran:
`mow config bind forward key key-code 16`
And got:
`thread 'main' panicked at src/main.rs:39:52:
called ``Result::unwrap()`` on an ``Err` `value: HidApiError { message: "hid_error is not implemented yet" }
note: run with ``RUST_BACKTRACE=1`` environment variable to display a backtrace`

**Comment by semedilino-073** [comment]
Ehmm, I misclicked :/

**Comment by korkje** [comment]
That's probably the hidapi failing, you can try running as root (with `sudo`) or create a "rules" file as described [here](https://github.com/korkje/mow/issues/13#issuecomment-1336020657).

**Comment by semedilino-073** [comment]
YOU'RE A GENIUS!! Sorry for that, but seriously, thanks! The solution was to just run the command as `sudo`. Thanks again!
